import type { BusRoute } from "./types";

export const BUS_ROUTES: BusRoute[] = [
  {
    service_no: "CW1", operator: "Causeway Link", route_name: "Kranji MRT → JB CIQ",
    sg_departure: "Kranji MRT", jb_arrival: "JB CIQ", via_checkpoint: "woodlands",
    fare_sgd: 1.6, fare_myr: 4.2, first_bus: "05:30", last_bus: "23:30",
    frequency_peak: "5-8 min", frequency_offpeak: "10-15 min",
    payment_methods: ["EZ-Link", "NETS", "Cash", "Visa Contactless"],
    typical_duration_min: 35, slug: "cw1",
    tips: "Board at Kranji MRT for the shortest wait. During peak hours, the queue at Kranji is much shorter than Queen Street. The bus drops off at JB CIQ immigration — clear customs and walk to JB Sentral or take a local bus.",
  },
  {
    service_no: "CW2", operator: "Causeway Link", route_name: "Queen Street → JB CIQ",
    sg_departure: "Queen Street Terminal", jb_arrival: "JB CIQ", via_checkpoint: "woodlands",
    fare_sgd: 1.8, fare_myr: 4.8, first_bus: "05:00", last_bus: "00:00",
    frequency_peak: "5-10 min", frequency_offpeak: "10-20 min",
    payment_methods: ["EZ-Link", "Cash"], typical_duration_min: 45, slug: "cw2",
    tips: "Queen Street is in the civic district near Bugis. Expect long queues on Friday evenings and Saturday mornings. Arrive 15 minutes before departure for a seat.",
  },
  {
    service_no: "170", operator: "SBS Transit", route_name: "Queen Street → Larkin Sentral",
    sg_departure: "Queen Street Terminal", jb_arrival: "Larkin Sentral", via_checkpoint: "woodlands",
    fare_sgd: 2.1, fare_myr: 5.5, first_bus: "05:15", last_bus: "23:45",
    frequency_peak: "6-10 min", frequency_offpeak: "12-18 min",
    payment_methods: ["EZ-Link", "NETS", "Cash"], typical_duration_min: 60, slug: "170",
    tips: "The 170 goes all the way to Larkin, making it ideal if your destination is further from JB Sentral. You stay on the same bus through immigration checkpoints.",
  },
  {
    service_no: "170X", operator: "SBS Transit", route_name: "Kranji MRT → JB Sentral",
    sg_departure: "Kranji MRT", jb_arrival: "JB Sentral", via_checkpoint: "woodlands",
    fare_sgd: 2.1, fare_myr: 5.5, first_bus: "06:00", last_bus: "22:00",
    frequency_peak: "8-12 min", frequency_offpeak: "15-20 min",
    payment_methods: ["EZ-Link", "NETS", "Cash"], typical_duration_min: 40, slug: "170x",
    tips: "170X is the express variant — fewer stops means a faster trip. Boards at Kranji MRT. Limited availability on weekends.",
  },
  {
    service_no: "950", operator: "SBS Transit", route_name: "Woodlands Int → JB CIQ",
    sg_departure: "Woodlands Interchange", jb_arrival: "JB CIQ", via_checkpoint: "woodlands",
    fare_sgd: 1.5, fare_myr: 4.0, first_bus: "05:30", last_bus: "23:00",
    frequency_peak: "7-10 min", frequency_offpeak: "12-18 min",
    payment_methods: ["EZ-Link", "NETS", "Cash"], typical_duration_min: 30, slug: "950",
    tips: "Cheapest option via Woodlands. Departs from the interchange which is connected to Woodlands MRT/TE line. Short crossing distance.",
  },
  {
    service_no: "CW3", operator: "Causeway Link", route_name: "Jurong Town Hall → JB (Tuas)",
    sg_departure: "Jurong Town Hall", jb_arrival: "JB CIQ 2nd Link", via_checkpoint: "tuas",
    fare_sgd: 3.5, fare_myr: 9.0, first_bus: "06:00", last_bus: "22:30",
    frequency_peak: "10-15 min", frequency_offpeak: "20-30 min",
    payment_methods: ["EZ-Link", "Cash"], typical_duration_min: 50, slug: "cw3",
    tips: "Via Tuas — longer ride but often less congested than Woodlands on weekends. Higher fare reflects the longer distance. Good alternative during Woodlands jams.",
  },
  {
    service_no: "160", operator: "SBS Transit", route_name: "Jurong Town Hall → JB Sentral (Tuas)",
    sg_departure: "Jurong Town Hall", jb_arrival: "JB Sentral", via_checkpoint: "tuas",
    fare_sgd: 3.2, fare_myr: 8.5, first_bus: "05:45", last_bus: "23:00",
    frequency_peak: "8-12 min", frequency_offpeak: "15-25 min",
    payment_methods: ["EZ-Link", "NETS", "Cash"], typical_duration_min: 55, slug: "160",
    tips: "The 160 uses the Tuas Second Link, which is less crowded but further from the city. Best if you're already in the west side of Singapore.",
  },
  {
    service_no: "CW7", operator: "Causeway Link", route_name: "Tuas Link MRT → JB CIQ",
    sg_departure: "Tuas Link MRT", jb_arrival: "JB CIQ 2nd Link", via_checkpoint: "tuas",
    fare_sgd: 2.8, fare_myr: 7.5, first_bus: "06:30", last_bus: "22:00",
    frequency_peak: "12-18 min", frequency_offpeak: "20-30 min",
    payment_methods: ["EZ-Link", "Cash"], typical_duration_min: 40, slug: "cw7",
    tips: "Boards right at Tuas Link MRT station. Lowest traffic option if you're crossing via Tuas. Limited frequency so check timing before heading over.",
  },
];
