import Link from "next/link";

export default function PrivacyPage() {
  return <div className="container max-w-3xl py-8 pb-mobile-nav">
    <h1 className="font-heading text-2xl font-bold">Privacy Policy</h1>
    <p className="mt-2 text-sm text-muted-foreground">Last updated: 10 October 2026</p>
    <div className="mt-8 space-y-7 text-sm leading-relaxed text-muted-foreground [&_h2]:mb-2 [&_h2]:font-heading [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-foreground [&_a]:text-accent [&_a]:underline">
      <section><h2>About this service</h2><p>SG Border Live is an independent Singapore–Johor crossing information project. It displays timestamped transport feeds, guides and calculators. It is not affiliated with any government agency. You can browse without creating an account.</p></section>
      <section><h2>Information involved in using the site</h2><p>Our hosting and infrastructure providers process technical request information, such as IP address, browser details, requested URL and request time, to deliver and secure the website. Transport data providers receive the technical information needed for requests made directly by your browser. This information should not be assumed to be anonymous.</p><p className="mt-2">Camera images come from LTA via data.gov.sg, and public bus arrival estimates come from ArriveLah/LTA. These are third-party transport observations, not location tracking of you. Calculator inputs are processed in your browser; the calculators do not ask for your name, passport or vehicle registration number.</p></section>
      <section><h2>Local storage and optional analytics</h2><p>We store your chosen display language under <code>sgborder-lang</code> and your analytics preference under <code>sgborder-analytics-choice</code> in your browser's local storage. You can clear these through your browser settings.</p><p className="mt-2">Google Analytics loads only after you choose “Allow analytics”. It uses cookies and device identifiers to measure page views, interactions, referring pages and browser/device information. Google processes request data including your IP address under its own policies. Choose “Decline analytics” to browse without loading it. Use “Analytics preferences” in the footer to change your choice; declining disables further collection by this page and clears the site's Google Analytics cookies. Previously collected information is not erased by changing that preference.</p><p className="mt-2">See <a href="https://policies.google.com/technologies/partner-sites">how Google uses information from partner sites</a>, <a href="https://policies.google.com/privacy">Google's privacy policy</a> and the <a href="https://tools.google.com/dlpage/gaoptout">Google Analytics opt-out add-on</a>.</p></section>
      <section><h2>Advertising</h2><p>SG Border Live loads Google AdSense for site verification and advertising. Ad availability depends on Google approval and account settings. Where required, separate advertising consent controls must be enabled before advertising starts. We will update this policy if additional advertising providers are introduced.</p><p className="mt-2">Google advertising services and their partners can use cookies, web beacons, IP addresses and device identifiers to deliver, measure and personalise advertisements based on visits to this and other sites. You can manage Google's personalised advertising through <a href="https://myadcenter.google.com/">My Ad Center</a>. Our analytics preference control is not an advertising consent platform.</p></section>
      <section><h2>Contact and external services</h2><p>For privacy enquiries, email <a href="mailto:hello@sgborder.live">hello@sgborder.live</a>. When you email us, your address and the information you provide are processed to review and respond to your request. Please send only information relevant to your enquiry.</p><p className="mt-2">The <Link href="/contact">contact and corrections page</Link> links to our public GitHub issue tracker. Submissions are public and governed by <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub's privacy policy</a>; do not post sensitive personal information. External agencies and operators have their own privacy practices.</p></section>
      <section><h2>Your choices and policy updates</h2><p>You can decline optional analytics, change the preference later, clear browser storage and use browser controls to limit cookies. This site is not directed at children under 13. We will update this page when our data practices change and show the revision date above. For questions about this policy, use the <Link href="/contact">contact page</Link>. Send individual privacy enquiries by email rather than posting personal details publicly.</p></section>
    </div>
  </div>;
}
